name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install  # Altere para seu gerenciador de pacotes

    - name: Build project
      run: npm run build  # Altere para seu comando de build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.AWS_SSH_HOST | split('@') | last }} >> ~/.ssh/known_hosts

    - name: Copy Files via SCP
      run: |
        scp -r dist/* ${{ secrets.AWS_SSH_HOST }}:/home/ubuntu/app

    - name: Run Post-Deploy Commands
      run: |
        ssh ${{ secrets.AWS_SSH_HOST }} "
          cd /home/ubuntu/app &&
          npm install --production &&
          pm2 restart all
        "
